version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: _dockerfiles/qxapp/python/Dockerfile
      args:
        serverdir: server-py-aiohttp
        web_outdir: /usr/src/app/client
    ports:
      - '9081:8080'
    environment:
      - SIMCORE_WEB_CONFIG=production
  
