version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: ./server-py-aiohttp/Dockerfile-prod
      args:
        serverdir: server-py-aiohttp
        web_outdir: /usr/src/app/client
        modelsdir: models
        models_outdir: /usr/src/models
    ports:
      - '9081:8080'
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
  flower:
    image: ondrejit/flower:latest
    command: --broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbit:5672
    ports:
      - 5555:5555
    depends_on:
      - rabbit
  sidecar:
    build:
      context: .
      dockerfile: ./sidecar/Dockerfile-prod
      args:
        modelsdir: models
        models_outdir: /work/models
    volumes:
      - input:/input
      - output:/output
      - log:/log
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbit
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  input:
  output:
  log:
  postgres: