version: '3'
services:
  webserver:
    image: masu.speag.com/simcore/comp.backend/webserver:1.4
    ports:
      - '9081:8080'
    environment:
      - SIMCORE_WEB_CONFIG=production
    deploy:
      placement:
        constraints: 
          - node.platform.os == linux
          - node.role == manager
