#!/bin/bash
if [[ "$1" == "test" ]]; then
    OUTPUT_FOLDER=`echo ${PWD}`
    INPUT_FOLDER=`echo ${PWD}`
    LOG_FOLDER=`echo ${PWD}`
fi

in_1=$INPUT_FOLDER/in_1
in_2=$INPUT_FOLDER/input.json

out_1=$OUTPUT_FOLDER/out_1
out_2=$OUTPUT_FOLDER/output.json

log_file=$LOG_FOLDER/log.dat

# in_1 is a file and is optional
# in_2 comes from parsing input.json and is optional
# out_1 is a file that will be craeted, non-optional (out_1)
# out_2 is a file that will be craeted, non-optional (output.json)

args=""
if [ -f $in_1 ]; then
    arg=" --in_1 $in_1"
    args=$args$arg
fi
if [ -f $in_2 ]; then
    param_in_2=$(cat $in_2 | jq ".in_2")
    arg=" --in_2 $param_in_2"
    args=$args$arg
fi
arg=" --out_1 $out_1 --out_2 $out_2 "
args=$args$arg

echo $args
#./sleeper --in_1 $in_1 --in_2 $param_in_2 --out_1 $out_1 >> $log_file
./sleeper $args >> $log_file
